### ISSUE TITLE
Transition from Weaviate v3 to v4: Issues with WeaviateHybridSearchRetriever and Document Import

### ISSUE THREAD

**Issue by lisascat** [weaviate/recipes#162]
Hello,

I am encountering issues while transitioning from Weaviate v3 to v4. In v3, I was using the following imports:

from langchain.retrievers.weaviate_hybrid_search import WeaviateHybridSearchRetriever
from langchain.schema import Document

My data comes from JSON, and I used to import the documents with this approach:
attributes = [
    "data",
    "hora_inicio_video",
    "hora_fim_video",
    "chave_unica",
    "summary_text",
    "highlights_assunto",
    "action_log",
    "location"
]

retriever = WeaviateHybridSearchRetriever(
    alpha=0.5, 
    client=client,
    index_name="RAG",
    text_key="page_content",
    attributes=attributes,
    create_schema_if_missing=True
)

documents = [
    Document(page_content=chunk['transcription'], metadata=chunk['metadata'])
    for chunk in data
]

retriever.add_documents(documents)

I was also filtering queries using metadata like this:
docs_and_scores = retriever.get_relevant_documents(
    query=query, 
    where_filter=metadata_query, 
)

I am now trying to transition to v4, but I'm having trouble figuring out the equivalent way to import the documents and query with metadata.

I attempted to use the following code for document import, but I am unsure if it's the correct approach:
db = WeaviateVectorStore.from_documents(documents, embedding=embeddings, client=client, index_name="RAG")

Could you please help me on how to properly adapt my code for Weaviate v4?

Thank you for your help!

**Comment by erika-cardenas** [comment]
Hi @lisascat, thanks for opening up the issue!
Are you using a notebook in this repository? From the [LangChain documentation](https://python.langchain.com/docs/integrations/vectorstores/weaviate/), it looks like you can import data like this:

```
weaviate_client = weaviate.connect_to_local()
db = WeaviateVectorStore.from_documents(docs, embeddings, client=weaviate_client)
```

and you can filter like this:
```
search_filter = Filter.by_property("source").equal("state_of_the_union.txt")
filtered_search_results = db.similarity_search(query, filters=search_filter, k=3)
assert len(filtered_search_results) <= 3
```

**Comment by lisascat** [comment]
It worked, thanks!

**Comment by lisascat** [comment]
It worked, tks!
