### ISSUE TITLE
Need of OpenAI requirement

### ISSUE THREAD

**Issue by pradeepdev-1995** [weaviate/recipes#18]
I am using the code in this official documentation

https://github.com/weaviate/recipes/blob/main/integrations/llama2-demo/notebook.ipynb

But unlike in the above code, I am using the hugging face embedding instead of the openai embedding. The rest is the same. 

But still, it asking for the openai credentials. Why it is so?

**Comment by erika-cardenas** [comment]
Hi Pradeep, 
By default LlamaIndex uses OpenAI, so you will have to configure your project to use HF. I'd recommend asking how to do this in their discord channel: https://discord.com/channels/1059199217496772688/1059200010622873741
