### ISSUE TITLE
Typo in recipe

### ISSUE THREAD

**Issue by rjalexa** [weaviate/recipes#36]
https://github.com/weaviate/recipes/blob/main/data-with-vectors/vector_search.ipynb

I believe that in the second example, the code:
`.with_additional(["distance", "vector, id"])`
should be
`.with_additional(["distance, vector, id"])`

Great example loved it.

**Comment by erika-cardenas** [comment]
Hi @rjalexa, 
Thanks so much for raising the issue! I was able to run both `.with_additional(["distance", "vector, id"])` and `.with_additional(["distance, vector, id"])` without any errors. I'm going to change it to each parameter in separate quotes to match the documentation: https://weaviate.io/developers/weaviate/api/graphql/additional-properties#available-additional-properties

Thanks again 😊

**Comment by erika-cardenas** [comment]
I also see the typo now with "vector" and "id" under one quote! I just pushed the update.

**Comment by rjalexa** [comment]
Thank you. Keep up the god work!
