### ISSUE TITLE
Will the LlamaIndex integration be compatible with the `v4` Weaviate client?

### ISSUE THREAD

**Issue by databyjp** [weaviate/recipes#39]
We had a user question about whether a `v4` version (flavour?) of [this recipe](https://github.com/weaviate/recipes/blob/main/integrations/llamaindex/simple-query-engine/simple-query-engine.py) exists.

Will this be updated to the v4 syntax, and does the LlamaIndex code / integration need a corresponding update?

**Comment by erika-cardenas** [comment]
Hey JP, 
We would need to update the LlamaIndex integration to use the `v4` client. Can we discuss this in the #community-solution-engineering channel?
