### ISSUE TITLE
Using DSPy with incomplete questions

### ISSUE THREAD

**Issue by davidwynter** [weaviate/recipes#47]
Hi,

I have a customer support chatbot. One of the issues I and I am sure many others face is the users' dialogue can fall into 3 categories:

1. Not relevant: E.g. "Hi Joel, how was your holiday?" Completely unrelated to the question the user might eventually ask.
2. Partial context:  Asks questions that give only part of the required context, E.g. "I have a problem with my Reports." When there are 24 different types of reports and is the problem with creating or outputting the report? 
3. Full context: Has everything required to answer the question. E.g. "I have a issue creating the gardening report, can you help?"

Currently I use GPT4 to classify the initial question and use exemplars for the common partial context, like above, to standardize responses. I use Weaviate as my vector store and have built a Knowledge Graph schema on top, to store all of my previous customer support conversation, including mapping question(s) to eventual answer(s). So can retrieve using Hybrid search and also triples related to entities in the question. 

I get the feeling that DSPy could really help the complexity here. Maybe you next video Connor? Enjoying your videos!

**Comment by CShorten** [comment]
Hey David! Thank you so much for opening this issue, amazing to learn about what you are trying to build!

I hope this notebook is useful to your problem - https://github.com/weaviate/recipes/blob/Issue-47/integrations/dspy/archived-issues/Dialogue-Classifier.ipynb.

Maybe a next step could be to retrieve relevant answers if the classification is `full context`. There is a quick snippet at the end of the notebook on how to connect Weaviate!

I would love to cover classification with dspy on one of these videos, amazing idea!

Thanks so much!

**Comment by erika-cardenas** [comment]
Hi @davidwynter, 
I hope the above notebook helps! I'm going to close this issue now. 🙂
