### ISSUE TITLE
WeaviateBlogRAG-0-0-0.json dataset

### ISSUE THREAD

**Issue by bhomass** [weaviate/recipes#56]
can we download this dataset from somewhere?

**Comment by erika-cardenas** [comment]
Hi @bhomass, thanks for your question! 🙂 

Sorry, we moved the `.json` when re-organizing the repo. You can find it [here](https://github.com/weaviate/recipes/files/14925303/WeaviateBlogRAG-0-0-0.json), and we'll add it back to the repository soon!
