### ISSUE TITLE
WeaviateClient has no attribute 'query'

### ISSUE THREAD

**Issue by koljanos** [weaviate/recipes#63]
Hey, I've got here from Connor Shorten's video about llama3 local video.
Hey, when running the `integrations/dspy/llms/Llama3.ipynb`
I get this error: `AttributeError: 'WeaviateClient' object has no attribute 'query'`
I have:
`dspy-ai = "^2.4.5"
langfuse = "^2.27.0"
weaviate-client = "^4.5.5"`
Installed, I've tried version 3 of weaviate-client, but got nowhere, help please :D

**Comment by erika-cardenas** [comment]
Hi @koljanos, 🙂 
Thanks so much for creating the issue! @CShorten will take a look and share the version requirements for DSPy and Weaviate soon.

**Comment by CShorten** [comment]
Hey @koljanos, apologies for this -- we are asking to rebuild the pypi package with the fix here - https://github.com/stanfordnlp/dspy/blob/main/dspy/retrieve/weaviate_rm.py#L85. In the meantime, would you be alright with building from source?

**Comment by koljanos** [comment]
Allright, will do, thanks a lot!!

**Comment by CShorten** [comment]
@erika-cardenas let's close after merging this one - https://github.com/stanfordnlp/dspy/pull/822. One more thing to be resolved I think.
