### ISSUE TITLE
Query call with protocol GRPC search failed with message could not find class WeaviateBlogChunk in schema

### ISSUE THREAD

**Issue by Deanozk** [weaviate/recipes#69]
I would suggest that this just be made available as some collection file that can be just uploaded. Every DSPy tutorial uses this but only one or two of them mentions that its a separate recipe to create this WeaviateBlogChunk in Weaviate.  I suggest that this just be made into an uploadable collection file somehow. Or we have a simpler process for creating the WeaviateBlogChunk collections. I have yet to get it working correctly.   If it's so easy why not just have single function that can be called from the other blog posts to create the collection? If its not, than I think its best to inform users they really need to start with that tutorial.

**Comment by erika-cardenas** [comment]
Hi @Deanozk, 
Thank you for the issue and great point. We can include the callout in all of the notebooks for consistency. People may have a running Weaviate cluster or data they want to use for the notebook, so we want to keep it flexible!

**Comment by joseagraz** [comment]
How was this resolved? I'm facing the same issue, but unclear how this issue was closed

WeaviateQueryError: Query call with protocol GRPC search failed with message <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "could not find class WeaviateBlogChunk in schema"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-03T16:56:50.626667684-04:00", grpc_status:2, grpc_message:"could not find class WeaviateBlogChunk in schema"}"
>.
